# Generated by Django 6.0.4 on 2026-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='yosh',
            field=models.PositiveIntegerField(blank=True, default=15),
        ),
    ]
